# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Beta CI

on:
    workflow_dispatch:
    push:
        tags:
            - "v*-*"

jobs:
    publish-core:
        defaults:
            run:
                working-directory: ./packages/core
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.21.1
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@debordewebsolutions'
            - name: Build
              run: npm install && npm run build
              working-directory: .
            - name: Publish to GitHub Packages
              run: npm publish --tag beta
              working-directory: ./packages/core
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    publish-cells:
        defaults:
            run:
                working-directory: ./packages/cells
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.21.1
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@debordewebsolutions'
            - name: Build
              run: npm install && npm run build
              working-directory: .
            - name: Publish to GitHub Packages
              run: npm publish --tag beta
              working-directory: ./packages/cells
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    publish-source:
        defaults:
            run:
                working-directory: ./packages/source
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22.21.1
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@debordewebsolutions'
            - name: Bootstrap
              run: npm install && npm run build
              working-directory: .
            - name: Publish to GitHub Packages
              run: npm publish --tag beta
              working-directory: ./packages/source
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
